// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0x17zESEUxKUDEdM26BIzwh_8hhsy5q8',
    appId: '1:671583924896:web:db50d4867f6c20c17ccfc5',
    messagingSenderId: '671583924896',
    projectId: 'ride-share-1b110',
    authDomain: 'ride-share-1b110.firebaseapp.com',
    storageBucket: 'ride-share-1b110.firebasestorage.app',
    measurementId: 'G-WT14CFL9L0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA56ZBz3aLGVJA7gN953IonmzWnSJFD4ac',
    appId: '1:671583924896:android:fbfee756a8d46c297ccfc5',
    messagingSenderId: '671583924896',
    projectId: 'ride-share-1b110',
    storageBucket: 'ride-share-1b110.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAhTthMEYmNRH5c1D9bYYjaqfYfncqsKE',
    appId: '1:671583924896:ios:60af9c00737b8b607ccfc5',
    messagingSenderId: '671583924896',
    projectId: 'ride-share-1b110',
    storageBucket: 'ride-share-1b110.firebasestorage.app',
    iosBundleId: 'com.example.rideShare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAhTthMEYmNRH5c1D9bYYjaqfYfncqsKE',
    appId: '1:671583924896:ios:60af9c00737b8b607ccfc5',
    messagingSenderId: '671583924896',
    projectId: 'ride-share-1b110',
    storageBucket: 'ride-share-1b110.firebasestorage.app',
    iosBundleId: 'com.example.rideShare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0x17zESEUxKUDEdM26BIzwh_8hhsy5q8',
    appId: '1:671583924896:web:2891d6d4234ff4217ccfc5',
    messagingSenderId: '671583924896',
    projectId: 'ride-share-1b110',
    authDomain: 'ride-share-1b110.firebaseapp.com',
    storageBucket: 'ride-share-1b110.firebasestorage.app',
    measurementId: 'G-M9PF3FVYWW',
  );

}